### PR TITLE
Update functions.inc.php

### PR DESCRIPTION
**Pull request by dartcafe**
Added a filter to select only groups which are configured for notification.

### CODE REVIEW

**Comment by dartcafe** [comment]
@plegall: Any chance to get this merged and released?

**Comment by plegall** [comment]
Hi @dartcafe 

Thank you for your patience!

Yes it's totally possible, but please modify your pull-request:

1. do not transform multiple lines SQL queries in a single line
2. do not remove the long comment after "notify users" (do another PR for this)

**Comment by dartcafe** [comment]
I reverted the last commit, so the only change is the filtering statement.

**Comment by dartcafe** [comment]
removal from personal PR list

**Pull request closed without merging**
